version: 2

models:
  - name: web_user_stitching
    columns:
      - name: anonymous_id
        tests:
          - unique
          - not_null

  - name: web_page_views__sessionized
    columns:
      - name: page_view_id
        tests:
          - unique
          - not_null

  - name: web_sessions__initial
    columns:
      - name: session_id
        tests:
          - unique
          - not_null

  - name: web_sessions__stitched
    columns:
      - name: session_id
        description: ''
        tests:
          - unique
          - not_null

  - name: web_sessions
    columns:
      - name: session_id
        description: ''
        tests:
          - unique
          - not_null
